# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Preset

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#394260"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[golang]
symbol = "ﳑ "

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#fca103 bg:#212736)]($style)'
